# Generated by Django 4.1.5 on 2023-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('km_driven', models.PositiveIntegerField()),
                ('purchase_date', models.DateField(null=True)),
            ],
        ),
    ]
