# Generated by Django 4.1.5 on 2023-02-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'petrol'), ('diesel', 'diesel'), ('ev', 'ev')], default='petrol', max_length=50),
        ),
    ]
